name: dws_visualisations
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - xarray
  - pip
  - plotly-resampler
  - netCDF4
  - jupyterlab
  - pip
  - pip:
      - dash[jupyterlab]
      - plotly
postBuild:
  - jupyter lab build
