name: dws_visualisations
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - xarray
  - pip
  - netCDF4
  - jupyterlab>=4.0  # Ensure JupyterLab is up-to-date
  - pip
  - pip:
      - dash[jupyterlab]
      - plotly
      - plotly-resampler
